### ISSUE TITLE
Enhancement Request: Period flush or a function call to flush BufferedMetricSink

### ISSUE THREAD

**Issue by rohitjoshi** [56quarters/cadence#100]
Most of the application will have varying traffic and may be very lower and may not reach the buffer size. Is it possible to provide a flush() function so application can call it periodically?

**Comment by 56quarters** [comment]
Hi @rohitjoshi ,
Sure, it's possible to add a flush method to the buffered sinks so that applications could periodically flush metrics. However, the buffer in the sink is only 512 bytes by default which ends up being about 10-20 metrics. If an your application isn't emitting enough metrics to fill the buffer, would the non-buffering `UdpMetricSink` be a better choice? Thanks!

**Comment by rohitjoshi** [comment]
@56quarters Due to the peak throughput requirement (500K+), I have increased buffer to 8196 and would like to periodically flush when volume is too low.

**Comment by 56quarters** [comment]
Got it, that makes sense. I think adding a `.flush()` method to the `MetricSink` trait makes sense in this case. Would that work for your usecase?

**Comment by rohitjoshi** [comment]
👍 Thank you 🙏

**Comment by rohitjoshi** [comment]
Can you please support `.flush()` method for `StatsdClient` object?  I am creating StatsdClient from `QueuingMetricSink` where flush method not available.

```
let uds_sink = BufferedUnixMetricSink::with_capacity(uds_path, socket, buffer_size);
let queuing_sink = QueuingMetricSink::from(uds_sink);
let client = StatsdClient::from_sink(&conf.prefix, queuing_sink);
```

**Comment by 56quarters** [comment]
I don't think it makes sense to add this very I/O focused method to the `StatsdClient`. You can solove this by keeping an `Arc<dyn MetricSink + Send + Sync>` around to the `QueuingMetricSink` in a another custom sink that wraps it and runs `.flush()` in a thread every N seconds or so.
