### ISSUE TITLE
Add UDP constructor to StatsClientBuilder

### ISSUE THREAD

**Issue by 56quarters** [56quarters/cadence#102]
Trying to deprecate and remove `StatsClient::from_udp_host()`, but it'd be nice to add something that allowed people to get up and running with less boiler plate.

Interface might look like:
```rust
let client = StatsdClientBuilder::from_udp_host(("metrics.example.com", 8125)).build();
```

Could also add a conditional method to create a client from a UNIX socket:
```rust
let client = StatsdClienBuilder::from_unix_socket("/run/statsd.sock").build();
```

**Comment by Diggsey** [comment]
This would be quite useful...

**Comment by 56quarters** [comment]
Well OK then

**Comment by 56quarters** [comment]
Actually, I'm going to close this again. It would be nice to get rid of some boilerplate but I don't love the idea of adding sink-specific methods to the `StatsdClientBuilder`. Additionally, this would kind of break the way the builder currently works where there aren't any actual public constructors (instead users call `StatsdClient::builder(sink)`).
