### ISSUE TITLE
Create logging metric sink for unit testing

### ISSUE THREAD

**Issue by jrconlin** [56quarters/cadence#103]
I would like to be sure that various metrics are being triggered during unit testing. 

To that end, it would be nice to be able to impl based off of MultiLineWriter so that I can query what's been generated so far. Unfortunately, it looks like that struct is pub(crate) and inaccessible.

Thanks!

**Comment by 56quarters** [comment]
Hi @jrconlin,
Thanks for the issue! I'd imagine this could be implemented as new sink specific for the purposes of testing that uses `MultiLineWriter` and exposes the wrapped `Write` implementation. Would that suffice for what you have in mind?

**Comment by jrconlin** [comment]
Yep! Basically, i just need a way to verify that the metric calls are being made and that the right values are being written. That should work fine.

**Comment by 56quarters** [comment]
Pushed a rough draft of what this might look like here: https://github.com/56quarters/cadence/compare/spy-sink

I'm not attached to the API so let me know if you can see a better way to do this. An example of how this sink could be used for verifying the contents sent can be found in the examples directory. Let me know what you think!

**Comment by jrconlin** [comment]
I like it, it's nice and simple.

The only thing I do worry about is the argument shift in
https://github.com/56quarters/cadence/compare/spy-sink#diff-7eba4868fedabfc34f9089b7d18fc58fL44
. I know it's minor, but just in case someone might be using that struct
for something, it'd be nice not having to go change it. Still, your call.
