### ISSUE TITLE
gauge is a u64 instead of a f64

### ISSUE THREAD

**Issue by craftytrickster** [56quarters/cadence#106]
The gauge method currently takes a u64 as seen below.

```rust
impl Gauged for StatsdClient {
    fn gauge_with_tags<'a>(&'a self, key: &'a str, value: u64) -> MetricBuilder<'_, '_, Gauge> {
        let fmt = MetricFormatter::gauge(&self.prefix, key, value);
        MetricBuilder::new(fmt, self)
    }
}
```

However, if you take a look at the datadog docs

https://docs.datadoghq.com/developers/metrics/types/?tab=gauge#example

> The Agent submits the last reported number, in this case 71.5, as the GAUGE metric’s value.

it clearly allows for floating point values. Can we please change this signature to accept a f64? I can open a PR if needed.

Thanks.

**Comment by 56quarters** [comment]
The types that Cadence is based on are from this document: https://github.com/b/statsd_spec in which a gauge is a `u64` value. Changing the type of the existing methods would be a disruptive and breaking change for current users. New methods that accept `f64` values could be added.

**Comment by craftytrickster** [comment]
Thank you for your response, adding a new trait of `FloatingGauged` would be fine with me.
It is worth noting that it seems to be somewhat ambiguous.

> The protocol allows for both integer and floating point values. Most implementations store values internally as a IEEE 754
double precision float, but many implementations and graphing systems only support integer values. For compatibility all values should be integers in the range (-2^53^, 2^53^).

Basically, it kind of sounds like floats actually are okay, just that some people won't actually implement their backends as such?
If this was my repo, I would add a FloatingGauged trait, but I would put it behind a cargo feature so that it isn't included by default, that way people would have to opt into it, when they knew for a fact their implementation supports the double precision float value.

What do you think?

**Comment by 56quarters** [comment]
That's a reasonable way to do it. However, I'll probably just add `*_float` or `*_f` methods to the existing `Gauged` trait.

**Comment by 56quarters** [comment]
Actually, I think I might end up going the route of making the `Gauged` trait generic. It might make sense to also apply this to other types as well. Off the top of my head:

Counters: float values don't make sense.
Timers: floats could make sense.
Histograms: floats could make sense.
Meter: floatsvalues don't make sense.
Set: unclear if float values make sense.

I'll take a survey of some other statsd client and server implementations to see what they do. Do you know of any other cases where most implementations use an `f64` value? 

In the mean time, an example

Example:
```rust
trait Gauged<T> {
    fn gauge(&self, key: &str, value: T) -> MetricResult<Gauge>;
    fn gauge_with_tags<'a>(&'a self, key: &'a str, value: T) -> MetricBuilder<'_, '_, Gauge>;
}

impl Gauged<u64> for StatsdClient { /* ... */ }
impl Gauged<f64> for StatsdClient { /* ... */ }
```
This shouldn't break most people's usage of Cadence unless they have their own implementation of `MetricClient`.

**Comment by craftytrickster** [comment]
I'm pretty new to the stats D world, I am probably not the best person to ask. The classifications you gave above do make intuitive sense though. I do know that at my current employer, they do accept certain things as a float value (gauge for example).

**Comment by 56quarters** [comment]
## Rust

* Dipstick appears to use accept most number-like things for gauges but uses [`isize` internally](https://github.com/fralalonde/dipstick/blob/e3e82f86a91a7e30e6a4b17f4e6af859a65546bc/src/input.rs#L208). For timers it uses `u64` values but converts to `isize`.
* rust-statsd uses [`f64` for gauges, timers, and histograms](https://github.com/markstory/rust-statsd/blob/4b9e30330a92811ca8d906613e0b2482368038d7/src/client.rs#L147).

## Go

* Cactus Statsd uses [`int64` for gauges and timers](https://github.com/cactus/go-statsd-client/blob/960992466b11fcb95fbf343efbea6583e167adba/statsd/client.go#L105)
* Alex Cesaro's Statsd client appears to accept [any number for gauges, timers, or histograms](https://github.com/alexcesaro/statsd/blob/7fea3f0d2fab1ad973e641e51dba45443a311a90/conn.go#L136)

## Java

* Micrometer uses a [`double` for gauges](https://github.com/micrometer-metrics/micrometer/blob/9b4910b72281d78adb808595d25cd4d8cdc17fa4/micrometer-core/src/main/java/io/micrometer/core/instrument/Gauge.java#L69) but generally works with anything based on [`Number`](https://github.com/micrometer-metrics/micrometer/blob/9b4910b72281d78adb808595d25cd4d8cdc17fa4/micrometer-core/src/main/java/io/micrometer/core/instrument/Gauge.java#L56)
* The Tim-Group statsd client accepts [`long` or `double` for gauges](https://github.com/tim-group/java-statsd-client/blob/ec75702a61af3daabd9c826f687243a3ee6fcde9/src/main/java/com/timgroup/statsd/StatsDClient.java#L84) and uses `long` for timers.

Based on this, I think it makes sense to add methods for `f64` gauges but keep other traits / methods as they are.

**Comment by craftytrickster** [comment]
Thank you for resolving this so quickly!
