### ISSUE TITLE
f64 support for distribution metric type

### ISSUE THREAD

**Issue by mbellani** [56quarters/cadence#131]
Thanks for [adding](https://github.com/56quarters/cadence/pull/125) distribution metric type support to cadence. It looks like the value types supported for distribution are only `u64`. There are cases however where distribution can be reported in fractions and it would be really great to either add that interface or change the type from `u64` to `f64`. DataDog's [datagram format](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics) does support both float and an integer, we currently use it this way in a custom metric type that we created. Also happy to open a PR if you like. 

Thanks for all your work this library.

**Comment by 56quarters** [comment]
A PR that [mirrors the way `f64` was added for gauges](https://github.com/56quarters/cadence/blob/master/cadence/src/client.rs#L117) would be great if you can, thanks!

**Comment by 56quarters** [comment]
Actually @mbellani, I've got some changes that I've been meaning to put up for a PR that will make the value for each metric call generic and remove the need for suffixed methods like `_duration` and `_f64`. Do you have an immediate need for an `f64` distribution type? If not, I'd rather not have you waste the work for something that's going to be deprecated imminently.

**Comment by mbellani** [comment]
@56quarters that sounds good to me, I'm not in a hurry, we currently have an implementation of `Distribution` metric that works pretty well and happy to switch whenever a more generic type support is added. I think generic type support would be great 👍🏽
