### ISSUE TITLE
Datadog Event stream support

### ISSUE THREAD

**Issue by rohitjoshi** [56quarters/cadence#147]
Any plan to support [DataDog event stream](https://docs.datadoghq.com/developers/events/dogstatsd/)?

I see @goyox86 has implemented Event support but it is not merged to latest. It would be good to add as an optional feature.

**Comment by 56quarters** [comment]
No, there are no plans to support DataDog event streams. As discussed in #70 it's a massive amount of functionality that I cannot support and is pretty far outside of what I'd expect a "statsd client" to have. There is an [extension trait](https://docs.rs/cadence/0.25.0/cadence/ext/trait.MetricBackend.html) that can be used for sending arbitrary things using the Cadence backend which may help you to build an event stream client outside of Cadence.
