### ISSUE TITLE
Support for UDS + SOCK_STREAM ? 

### ISSUE THREAD

**Issue by mlowicki** [56quarters/cadence#205]
Hey,

We've internal agent handling now Unix socket of type `SOCK_STREAM`. It works by first sending 4 bytes in little-endian which is the size of the following data and sending actual data. I could introduce something like `UnixStreamMetricSink` into `cadence`, opinions? Alternatively I was thinking about making `MultiLineWriter` and relevant methods public so I would implement such sink on my side but would prefer to not duplicate logic of the `MultiLineWriter` at least.

**Comment by 56quarters** [comment]
> I could introduce something like UnixStreamMetricSink into cadence, opinions?

I'm not opposed to this but I'd slightly prefer to make `MultiLineWriter` public.

> Alternatively I was thinking about making MultiLineWriter and relevant methods public so I would implement such sink on my side

This seems reasonable to me. It could be exposed via the `cadence::ext` module. WDYT?

**Comment by mlowicki** [comment]
> > I could introduce something like UnixStreamMetricSink into cadence, opinions?
> 
> I'm not opposed to this but I'd prefer to make `MultiLineWriter` public.
> 
> > Alternatively I was thinking about making MultiLineWriter and relevant methods public so I would implement such sink on my side
> 
> This seems reasonable to me. It could be exposed via the `cadence::ext` module. WDYT?

Sounds good. Can you take a look at https://github.com/56quarters/cadence/pull/206 ? With those I was able to implement sink backed by unix stream socket and still reuse `SocketStats` and `MultiLineWriter`.
